* Learning Metacompilers

** Reading List

*** Meta II: Original Paper
http://www.ibm-1401.info/Meta-II-schorre.pdf

*** Alan Kay interview with Joe Armstrong

A really great watch. Has a wealth of information about how we got where we are now.
https://www.youtube.com/watch?v=fhOHn9TClXY

** Materials Read

*** Meta II: An Early Compiler
http://onfoodandcoding.blogspot.com/2013/02/meta-ii-early-meta-compiler.html
Breezy read on the fun author had on implementing Meta II and what he learnt from it.

*** Review on ACM
[[https://queue.acm.org/detail.cfm?id=2724586][META II: Digital Vellum in the Digital Scriptorium]]
As the quote that appears at the end of the essay:

"J'ai seulement fait ici un amas de fleurs étrangères, n'y ayant fourni du mien que le filet à les lier." ("I have gathered a posy of other men's flowers, and nothing but the thread that binds them is mine own.") — Montaigne, Essais, 1595

Readable for the thread the author weaves, but if one is looking to understand the paper deeply, I think, going down the hands-on route is the best way as the paper is about technique as much as theory.

